"""Phase 1: initial schema

Revision ID: 82f661634ae6
Revises: 
Create Date: 2026-08-17 15:53:54.818765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f661634ae6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'admin', name='role', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('accommodation', sa.Enum('standard', 'time_and_a_half', 'double_time', name='accommodation', native_enum=False), nullable=False),
    sa.Column('exam_type', sa.String(length=64), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('current_score', sa.Integer(), nullable=True),
    sa.Column('goal_score', sa.Integer(), nullable=True),
    sa.Column('email_opt_in', sa.Boolean(), nullable=False),
    sa.Column('study_days', sa.JSON(), nullable=True),
    sa.Column('calendar_synced', sa.Boolean(), nullable=False),
    sa.Column('pro_expires_at', sa.DateTime(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('is_predicted_test', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='attemptstatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('accommodation_snapshot', sa.Enum('standard', 'time_and_a_half', 'double_time', name='accommodation', native_enum=False), nullable=False),
    sa.Column('is_practice', sa.Boolean(), nullable=False),
    sa.Column('feedback_nps', sa.Integer(), nullable=True),
    sa.Column('feedback_difficulty', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Enum('rw', 'math', name='section', native_enum=False), nullable=False),
    sa.Column('module_number', sa.Integer(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('calculator_allowed', sa.Boolean(), nullable=False),
    sa.Column('difficulty_variant', sa.Enum('easy', 'hard', 'fixed', name='modulevariant', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.Enum('pdf', 'docx', 'md', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'parsing', 'parsed', 'failed', name='importstatus', native_enum=False), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['question_banks.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('mcq', 'grid_in', name='questiontype', native_enum=False), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('authored', 'imported', name='questionsource', native_enum=False), nullable=False),
    sa.Column('acceptable_answers', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['question_banks.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempt_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_difficulty_label', sa.String(length=64), nullable=True),
    sa.Column('resolved_variant', sa.Enum('easy', 'hard', 'fixed', name='modulevariant', native_enum=False), nullable=True),
    sa.Column('effective_time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('break_started_at', sa.DateTime(), nullable=True),
    sa.Column('break_ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['exam_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempt_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('rw', sa.Integer(), nullable=False),
    sa.Column('math', sa.Integer(), nullable=False),
    sa.Column('per_topic', sa.JSON(), nullable=True),
    sa.Column('per_difficulty_time', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_table('choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=2), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_module_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['exam_modules.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_import_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_stem', sa.Text(), nullable=True),
    sa.Column('parsed_choices', sa.JSON(), nullable=True),
    sa.Column('parsed_answer', sa.Text(), nullable=True),
    sa.Column('answer_source', sa.Enum('extracted', 'ai_generated', 'missing', name='answersource', native_enum=False), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('suggested_topic', sa.String(length=128), nullable=True),
    sa.Column('suggested_difficulty', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'approved', 'edited', 'rejected', name='importitemstatus', native_enum=False), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('resulting_question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['question_imports.id'], ),
    sa.ForeignKeyConstraint(['resulting_question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', name='reportstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('choice_id', sa.Integer(), nullable=True),
    sa.Column('free_response_text', sa.String(length=255), nullable=True),
    sa.Column('marked_for_review', sa.Boolean(), nullable=False),
    sa.Column('strikethrough_state', sa.JSON(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['choice_id'], ['choices.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('question_reports')
    op.drop_table('question_import_items')
    op.drop_table('exam_module_questions')
    op.drop_table('choices')
    op.drop_table('attempt_scores')
    op.drop_table('attempt_modules')
    op.drop_table('questions')
    op.drop_table('question_imports')
    op.drop_table('exam_modules')
    op.drop_table('attempts')
    op.drop_table('question_banks')
    op.drop_table('exams')
    op.drop_table('teachers')
    op.drop_table('students')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
