"""Phase 15: question image_url and passage_text

Revision ID: f3a60456593d
Revises: 2910a32d5ee1
Create Date: 2026-08-21 23:33:52.655963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a60456593d'
down_revision = '2910a32d5ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passage_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('passage_text')

    # ### end Alembic commands ###
